### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by eugelogic** [SimeonGriggs/sanity-backup-s3#1]
Hi Simeon,
Thanks for all the awesome free content you share
I noticed a broken link on the README file of this repo
the `better guide to this App on my website` leads to an empty page on your website
https://www.simeongriggs.dev/backup-sanity-io-to-aws-s3
the correct link is https://www.simeongriggs.dev/backup-sanity-to-aws-s3
sorry I'm not practical opening pull requests on other people's repos

**Comment by SimeonGriggs** [comment]
Thanks for letting me know. Fixed it!
